eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1000/eureka/
spring:
  application:
    name: service-feign

  cloud:
    loadbalancer:
      retry:
        #该参数用来开启重试机制，默认是关闭
        enabled: true
server:
  port: 8080


ribbon:
  OkToRetryOnAllOperations: false #对所有操作请求都进行重试,默认false
  ReadTimeout: 3000   #负载均衡超时时间，默认值5000
  ConnectTimeout: 1000 #ribbon请求连接的超时时间，默认值2000
  MaxAutoRetries: 1     #同一台实例最大重试次数,不包括首次调用，默认0
  MaxAutoRetriesNextServer: 2 #切换实例的次数,默认1. 因此总调用的请求数是 (1+MaxAutoRetries)*(MaxAutoRetriesNextServer+1)

hystrix:
  command:
    default:  #default全局有效，service id指定应用有效
      execution:
        timeout:
          #是否开启超时熔断
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 19000 #断路器超时时间，默认1000ms



logging:
  level:
    com.netflix: info

feign:
  hystrix:
    enabled: true
